services:
  datagen:
    image: materialize/datagen
    environment:
      POSTGRES_HOST: ${NEON_HOST}
      POSTGRES_USER: ${NEON_USERNAME}
      POSTGRES_PASSWORD: ${NEON_PASSWORD}
      POSTGRES_DB: ${NEON_DATABASE}
      POSTGRES_SSLMODE: true
    entrypoint: >
      datagen
      -s /app/schemas/ingest-traffic-data.sql
      -n 1000
      -f postgres
      -w 100
    volumes:
      - ./ingest-traffic-data.sql:/app/schemas/ingest-traffic-data.sql