services:
  datagen:
    image: materialize/datagen
    entrypoint: >
      datagen
      -s /app/schemas/ingest-traffic-data.sql
      -n 1000
      -f postgres
      --connection-url postgres://${NEON_USERNAME}:${NEON_PASSWORD}@${NEON_HOST}:5432/${NEON_DATABASE}?sslmode=require
      -w 100
    volumes:
      - ./ingest-traffic-data.sql:/app/schemas/ingest-traffic-data.sql