name: Jadwal Shalat
on:
  schedule:
  - cron: '10 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install depedencies
      run: pip install psycopg2-binary==2.9.10 pytz==2025.2 requests==2.32.4

    - name: jalankan script main.py
      env:
        NEONDB_URI: ${{ secrets.NEONDB_URI }}
        TELEGRAM_URI: ${{ secrets.TELEGRAM_URI }}
      run: python main.py
    
